GET http://localhost:9999/story

###
GET http://localhost:9999/categories/

###
POST http://localhost:9999/users/register/
Content-Type: application/json

{
  "userName": "sad",
  "phoneNumber": "021510",
  "password": "Pass1111",
  "email": "dsa@gmail.com"
}

###
POST http://localhost:9999/story/create_story
Content-Type: application/json

{
  "name": "story 1",
  "author": "author 1",
  "description": "des 1",
  "categories": [

  ]
}

###
GET http://localhost:9999/comment

###
Post http://localhost:9999/comment
Content-Type: application/json

{
  "userId": "sad",
  "storyId": "sas",
  "comment": "safas"

}


### Get following Story
GET http://localhost:9999/story/follows
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWU1NzY0NjVlNjlhMGJkYzZhMTE4MGYiLCJpYXQiOjE3MTAwMDQ0MTUsImV4cCI6MTcxMDAwODAxNX0.oN2N6wJsUgHo3hWC-P29hxQxCdwWnJA6BvmQ-OHb8I8


### Follow Story
Post http://localhost:9999/story/follow/65ec57031b16e9468e67a227
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWU1NzY0NjVlNjlhMGJkYzZhMTE4MGYiLCJpYXQiOjE3MTAwMDQ0MTUsImV4cCI6MTcxMDAwODAxNX0.oN2N6wJsUgHo3hWC-P29hxQxCdwWnJA6BvmQ-OHb8I8


### Unfollow Story
Post http://localhost:9999/story/unfollow/65ec57031b16e9468e67a227
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWU1NzY0NjVlNjlhMGJkYzZhMTE4MGYiLCJpYXQiOjE3MTAwMDQ0MTUsImV4cCI6MTcxMDAwODAxNX0.oN2N6wJsUgHo3hWC-P29hxQxCdwWnJA6BvmQ-OHb8I8

